import assert from 'node:assert/strict';
import fixtures from './fixtures/ai-task-activity.json';
import { activitySchema } from '../src/lib/ai-activity';
import { mergeHandoffs, handoffsForTask } from '../src/lib/ai-handoffs';
import { emptyTotals, publicYear, type UsageYear } from '../src/lib/ai-usage';
import { taskDate, taskTitle, selectTaskPeriod, type AiTask } from '../src/lib/ai-task-records';
for (const f of fixtures) assert.equal(activitySchema.safeParse(f.activity).success, f.valid, f.name);
const activity = (name: string) => activitySchema.parse(fixtures.find(f => f.name === name)!.activity);
const base: AiTask = { id: 'sender-task', project: 'sender-project', type: null, status: 'completed', verification: [], rework: null, conflict: false, totals: emptyTotals() };
const a = activity('handoff_dispatch_accepted');
const h = a.handoffs![0];
const sender = { ...base, id: h.from.taskId ?? base.id, project: h.from.project, activity: a };
const receiver = { ...base, id: h.to.taskId ?? 'recipient-task', project: h.to.project, activity: structuredClone(a) };
assert.equal(mergeHandoffs([sender, sender, receiver])[0].events.length, h.events.length);
assert.equal(mergeHandoffs([sender, receiver])[0].conflict, false);
assert.equal(handoffsForTask(receiver, mergeHandoffs([sender])).length, 1);
const changed = structuredClone(receiver);
changed.activity.handoffs![0].events[0].summary = 'conflicting event';
assert.equal(mergeHandoffs([sender, changed])[0].conflict, true);
assert.equal(mergeHandoffs([sender, changed])[0].events.length, h.events.length + 1);
const headerConflict = structuredClone(receiver); headerConflict.activity.handoffs![0].request = 'different request';
assert.equal(mergeHandoffs([sender, headerConflict])[0].headers.length, 2);
assert.equal(mergeHandoffs([sender, headerConflict])[0].conflict, true);
const year: UsageYear = { year: 2026, weeks: [], devices: [], tasks: [sender], quality: { problems: [], fallback_identities: 0, task_conflicts: 0, ambiguous_task_responses: 0, comparison: 'withheld' }, fieldObservations: {} };
const projected = JSON.stringify(publicYear(year));
assert.equal(projected.includes(h.id), false); assert.equal(projected.includes('handoffs'), false); assert.equal(projected.includes('activity'), false);
const dateTask = { ...base, activity: activity('verified_date_only') };
assert.equal(taskDate(dateTask)?.basis, 'record');
const selected = selectTaskPeriod([dateTask, { ...base, activity: activity('label_date_only') }], year, 'year', 'newest', new Date('2026-10-02T00:00:00Z'));
assert.equal(selected.dated.length, 1); assert.equal(selected.undated.length, 1);
console.log(`${fixtures.length} canonical activity fixtures passed; handoff dedup/conflicts, private projection and date-only checks passed`);

assert.equal(handoffsForTask({ ...receiver, activity: undefined }, mergeHandoffs([sender])).length, h.to.taskId ? 1 : 0);
const complete = structuredClone(receiver);
complete.activity.handoffs![0].events = [{ ...h.events[0], id: 'done', kind: 'completed', reportedBy: 'recipient', result: { summary: 'done', artifacts: [], verification: null } }];
const failed = structuredClone(receiver);
failed.activity.handoffs![0].events = [{ ...h.events[0], id: 'failed', kind: 'failed', reportedBy: 'recipient', result: { summary: 'failed', artifacts: [], verification: null } }];
assert.equal(mergeHandoffs([complete, failed])[0].conflict, true);
const unknownTiming = { ...dateTask, presentation: { title: 'legacy', summary: 'legacy', occurredAt: '2026-10-02T00:00:00Z', checks: [], followUps: [], knowledge: [], evidence: [] }, activity: activity('all_unknown') };
assert.equal(taskDate(unknownTiming), null);
const { ingestSchema } = await import('../src/lib/ai-usage');
const envelope = { schema: 1, metrics: 'usage-v1', sequence: 1, sourceRevision: 'a'.repeat(40), generatedAt: '2026-10-02T00:00:00Z', years: [year], improvements: [] };
assert.equal(ingestSchema.safeParse(envelope).success, true);
assert.equal(ingestSchema.safeParse({ ...envelope, years: [{ ...year, tasks: [{ ...sender, project: 'unrelated', id: 'unrelated' }] }] }).success, false);
// 보완 설명이 없는 기록은 모두 같은 문구가 아니라 작업 ID 로 구분돼야 한다
assert.equal(taskTitle({ ...base, id: '2026-09-30-blog-thumbnail-title' }), 'blog thumbnail title');
assert.equal(taskTitle({ ...base, id: 'dev-bootstrap-git-ownership-20260930' }), 'dev bootstrap git ownership');
assert.equal(taskTitle({ ...base, id: '2026-09-30' }), '2026-09-30');
