import assert from "node:assert/strict";
import { ingestSchema, publicYear, emptyTotals, visibleWeeks, publicationSchema, type UsageYear } from "../src/lib/ai-usage";
import { slugSchema } from "../src/lib/validation";
const totals = { ...emptyTotals(), input: 100, cache_read: 60, output: 20, total: 120, non_cache_read_input: 40, responses: 1 };
const week = { week: "2026-09-28", ended: false, observed: true, partial: true, totals, groups: [{ project: "PRIVATE_PROJECT", tool: "Codex" as const, model: "PRIVATE_MODEL", effort: "PRIVATE_EFFORT", totals }], states: { unclassified: totals }, diagnostics: {} };
const year: UsageYear = { year: 2026, weeks: [week], devices: [{ device: "PRIVATE_DEVICE", since: "2026-09-28T00:00:00Z", until: "2026-09-30T00:00:00Z" }], tasks: [], quality: { problems: [], fallback_identities: 0, task_conflicts: 0, ambiguous_task_responses: 0, comparison: "withheld" }, fieldObservations: { cache_read: 1 } };
const publicData = publicYear(year);
assert.equal(JSON.stringify(publicData).includes("PRIVATE"), false);
assert.equal(publicData.weeks[0].totals.total, 120);
assert.equal(publicData.weeks[0].tools[0].totals.total, 120);
assert.equal(publicData.cacheObserved, true);
assert.equal(publicYear({ ...year, fieldObservations: {} }).cacheObserved, false);
assert.equal(publicYear({ ...year, weeks: [week, { ...week, week: "2026-09-21" }] }).cacheObserved, false);
const envelope = { schema: 1, metrics: "usage-v1", sequence: 1, sourceRevision: "a".repeat(40), generatedAt: "2026-09-30T00:00:00Z", years: [year], improvements: [] };
// Diagnostics are required and validated, not inferred from missing fields.
const keys = ["calls", "outputs", "output_chars", "large_outputs", "truncations", "repeated_calls", "known_failed_outputs", "unknown_output_outcomes", "kb_searches", "kb_empty_searches", "kb_selections", "kb_applications", "kb_search_mentions", "compactions"];
week.diagnostics = Object.fromEntries(keys.map(k => [k, 0]));
assert.ok(ingestSchema.safeParse(envelope).success);
assert.equal(ingestSchema.safeParse({ ...envelope, schema: 2 }).success, false);
assert.equal(ingestSchema.safeParse({ ...envelope, years: [year, year] }).success, false);
assert.equal(ingestSchema.safeParse({ ...envelope, years: [{ ...year, weeks: [week, week] }] }).success, false);
assert.equal(ingestSchema.safeParse({ ...envelope, years: [{ ...year, weeks: [{ ...week, week: "2026-09-29" }] }] }).success, false);
assert.equal(ingestSchema.safeParse({ ...envelope, years: [{ ...year, weeks: [{ ...week, totals: { ...totals, total: 999 } }] }] }).success, false);
assert.equal(ingestSchema.safeParse({ ...envelope, rawText: "private" }).success, false);
assert.equal(visibleWeeks([{ week: "2026-08-24" }, { week: "2026-09-28" }], "4", new Date("2026-09-30T00:00:00Z")).length, 1);
assert.equal(visibleWeeks([{ week: "2025-12-01" }, { week: "2025-12-29" }], "4", new Date("2026-09-30T00:00:00Z")).length, 1);
assert.equal(slugSchema.safeParse("ai").success, false);
assert.equal(publicationSchema.safeParse({ kind: "improvement", title: "", body: "x", date: "2026-09-30", postId: null, published: true }).success, false);
console.log("AI usage: 17 schema, privacy, totals, period and publication assertions passed");
